apiVersion: v1
kind: Pod
metadata:
  namespace: apache
  name: drillbit-pod
spec:
      containers:
      - name: drillbit
        imagePullPolicy: Always
        image: drill/apache-drill-ubuntu:1.13.0
        ports:
        - containerPort: 8047
          name: http
        - containerPort: 31010
          name: userport
        - containerPort: 31011
          name: controlport
        - containerPort: 31012
          name: dataport
