apiVersion: v1
kind: Pod
metadata:
  namespace: apache
  name: zookeeper-pod
spec:
      containers:
      - name: zookeeper
        imagePullPolicy: Always
        image: drill/apache-zookeeper-ubuntu:3.4.10
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
