apiVersion: v1
kind: Pod
metadata:
  name: drill1
spec:
      containers:
      - name: drill1
        imagePullPolicy: Always
        image: drill/apache-drill-centos:1.13.0
        ports:
        - containerPort: 8047
          name: http
        - containerPort: 30010
          name: server
        - containerPort: 30011
          name: server1
