apiVersion: v1
kind: Service
metadata:
  namespace: apache
  name: zookeeper-service
spec:
  ports:
  - name: client
    port: 2181
  - name: server
    port: 2888
  - name: leader-election
    port: 3888
  selector:
   app: zookeeper-app
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: apache
  name: zookeeper-set
spec:
  serviceName: zookeeper-service
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - zookeeper-app
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: zookeeper-pod
        imagePullPolicy: Always
        image: agirish/zookeeper:1.14.0
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
